[
    {
        "id": "1",
        "name": "Farmer Bob 垂耳兔",
        "price": 25000,
        "auther": "@ The Farmer Bob",
        "img": "../toy/2.png",
        "image1": "https://raw.githubusercontent.com/andy-28/toy/main/a01.png",
        "image2": "https://raw.githubusercontent.com/andy-28/toy/main/a02.png",
        "image3": "https://raw.githubusercontent.com/andy-28/toy/main/a03.png",
        "image4": "https://raw.githubusercontent.com/andy-28/toy/main/a04.png",
        "currency": "ETH"
    },
    {
        "id": "2",
        "name": "白色戰損Labubu",
        "auther": "@ kasinglung",
        "price": 35000,
        "img": "https://raw.githubusercontent.com/andy-28/toy/main/3.png",
        "image1": "https://raw.githubusercontent.com/andy-28/toy/main/b01.png",
        "image2": "https://raw.githubusercontent.com/andy-28/toy/main/b02.png",
        "image3": "https://raw.githubusercontent.com/andy-28/toy/main/b03.png",
        "image4": "https://raw.githubusercontent.com/andy-28/toy/main/b04.png",
        "currency": "ETH"
    },
    {
        "id": "3",
        "name": "Sooya Kokoala 賊貓貓",
        "auther": "@ Sooya",
        "price": 12000,
        "img": "https://raw.githubusercontent.com/andy-28/toy/main/4.png",
        "image1": "https://raw.githubusercontent.com/andy-28/toy/main/m01.png",
        "image2": "https://raw.githubusercontent.com/andy-28/toy/main/m02.png",
        "image3": "https://raw.githubusercontent.com/andy-28/toy/main/m03.png",
        "image4": "https://raw.githubusercontent.com/andy-28/toy/main/m04.png",
        "currency": "ETH"
    },
    {
        "id": "4",
        "name": "Farmer Bob x LV x Supreme",
        "auther": "@ The Farmer Bob",
        "price": 15000,
        "img": "https://raw.githubusercontent.com/andy-28/toy/main/5.png",
        "image1": "https://raw.githubusercontent.com/andy-28/toy/main/d01.png",
        "image2": "https://raw.githubusercontent.com/andy-28/toy/main/d02.png",
        "image3": "https://raw.githubusercontent.com/andy-28/toy/main/d03.png",
        "image4": "https://raw.githubusercontent.com/andy-28/toy/main/d04.png",
        "currency": "ETH"
    },
    {
        "id": "5",
        "name": "Dimoo BBM 柴郡貓 夢遊仙境",
        "auther": "@ AYAN DENG",
        "price": 7500,
        "img": "https://raw.githubusercontent.com/andy-28/toy/main/6.png",
        "image1": "https://raw.githubusercontent.com/andy-28/toy/main/e01.png",
        "image2": "https://raw.githubusercontent.com/andy-28/toy/main/e02.png",
        "image3": "https://raw.githubusercontent.com/andy-28/toy/main/e03.png",
        "image4": "https://raw.githubusercontent.com/andy-28/toy/main/e04.png",
        "currency": "ETH"
    },
    {
        "id": "6",
        "name": "Little BAD off 熊孩子",
        "auther": "@ littlebad",
        "price": 3500,
        "img": "https://raw.githubusercontent.com/andy-28/toy/main/7.png",
        "image1": "https://raw.githubusercontent.com/andy-28/toy/main/f01.png",
        "image2": "https://raw.githubusercontent.com/andy-28/toy/main/f02.png",
        "image3": "https://raw.githubusercontent.com/andy-28/toy/main/f03.png",
        "image4": "https://raw.githubusercontent.com/andy-28/toy/main/f04.png",
        "currency": "ETH"
    },
    {
        "id": "7",
        "name": "Zsiga 森林 Get Lost",
        "auther": "@ Zsiga",
        "price": 350,
        "img": "https://raw.githubusercontent.com/andy-28/toy/main/8.png",
        "image1": "https://raw.githubusercontent.com/andy-28/toy/main/g01.png",
        "image2": "https://raw.githubusercontent.com/andy-28/toy/main/g02.png",
        "image3": "https://raw.githubusercontent.com/andy-28/toy/main/g03.png",
        "image4": "https://raw.githubusercontent.com/andy-28/toy/main/g04.png",
        "currency": "ETH"
    },
    {
        "id": "8",
        "name": "刺蝟羊",
        "auther": "@ Sentire",
        "price": 2000,
        "img": "https://raw.githubusercontent.com/andy-28/toy/main/9.png",
        "image1": "https://raw.githubusercontent.com/andy-28/toy/main/h01.png",
        "image2": "https://raw.githubusercontent.com/andy-28/toy/main/h02.png",
        "image3": "https://raw.githubusercontent.com/andy-28/toy/main/h03.png",
        "image4": "https://raw.githubusercontent.com/andy-28/toy/main/h04.png",
        "currency": "ETH"
    },
    {
        "id": "9",
        "name": "Sooya boo",
        "auther": "@ Sooya",
        "price": 6500,
        "img": "https://raw.githubusercontent.com/andy-28/toy/main/10.png",
        "image1": "https://raw.githubusercontent.com/andy-28/toy/main/i01.png",
        "image2": "https://raw.githubusercontent.com/andy-28/toy/main/i02.png",
        "image3": "https://raw.githubusercontent.com/andy-28/toy/main/i03.png",
        "image4": "https://raw.githubusercontent.com/andy-28/toy/main/i04.png",
        "currency": "ETH"
    },
    {
        "id": "10",
        "name": "Milolo聆聽者",
        "auther": "@ 橘久月",
        "price": 4000,
        "img": "https://raw.githubusercontent.com/andy-28/toy/main/11.png",
        "image1": "https://raw.githubusercontent.com/andy-28/toy/main/j01.png",
        "image2": "https://raw.githubusercontent.com/andy-28/toy/main/j02.png",
        "image3": "https://raw.githubusercontent.com/andy-28/toy/main/j03.png",
        "image4": "https://raw.githubusercontent.com/andy-28/toy/main/j04.png",
        "currency": "ETH"
    },
    {
        "id": "11",
        "name": "Dora 大表姐",
        "auther": "@ Dora",
        "price": 400,
        "img": "https://raw.githubusercontent.com/andy-28/toy/main/12.png",
        "image1": "https://raw.githubusercontent.com/andy-28/toy/main/k01.png",
        "image2": "https://raw.githubusercontent.com/andy-28/toy/main/k02.png",
        "image3": "https://raw.githubusercontent.com/andy-28/toy/main/k03.png",
        "image4": "https://raw.githubusercontent.com/andy-28/toy/main/k04.png",
        "currency": "ETH"
    },
    {
        "id": "12",
        "name": "Farmer Bob x 瑪莎拉蒂",
        "auther": "@ The Farmer Bob",
        "price": 9000,
        "img": "https://raw.githubusercontent.com/andy-28/toy/main/13.png",
        "image1": "https://raw.githubusercontent.com/andy-28/toy/main/l01.png",
        "image2": "https://raw.githubusercontent.com/andy-28/toy/main/l02.png",
        "image3": "https://raw.githubusercontent.com/andy-28/toy/main/l03.png",
        "image4": "https://raw.githubusercontent.com/andy-28/toy/main/l04.png",
        "currency": "ETH"
    },
    {
        "id": "13",
        "name": "Eva戰損Labubu",
        "auther": "@ kasinglung",
        "price": 25000,
        "img": "https://raw.githubusercontent.com/andy-28/toy/main/14.png",
        "image1": "https://raw.githubusercontent.com/andy-28/toy/main/c01.png",
        "image2": "https://raw.githubusercontent.com/andy-28/toy/main/c02.png",
        "image3": "https://raw.githubusercontent.com/andy-28/toy/main/c03.png",
        "image4": "https://raw.githubusercontent.com/andy-28/toy/main/c04.png",
        "currency": "ETH"
    },
    {
        "id": "14",
        "name": "Milolo樂團指揮家",
        "auther": "@ 橘久月",
        "price": 4500,
        "img": "https://raw.githubusercontent.com/andy-28/toy/main/15.png",
        "image1": "https://raw.githubusercontent.com/andy-28/toy/main/n01.png",
        "image2": "https://raw.githubusercontent.com/andy-28/toy/main/n02.png",
        "image3": "https://raw.githubusercontent.com/andy-28/toy/main/n03.png",
        "image4": "https://raw.githubusercontent.com/andy-28/toy/main/n04.png",
        "currency": "ETH"
    },
    {
        "id": "15",
        "name": "Molly x BURBERRY",
        "auther": "@ KENNY WONG",
        "price": 5600,
        "img": "https://raw.githubusercontent.com/andy-28/toy/main/16.png",
        "image1": "https://raw.githubusercontent.com/andy-28/toy/main/o01.png",
        "image2": "https://raw.githubusercontent.com/andy-28/toy/main/o02.png",
        "image3": "https://raw.githubusercontent.com/andy-28/toy/main/o03.png",
        "image4": "https://raw.githubusercontent.com/andy-28/toy/main/o04.png",
        "currency": "ETH"
    },
    {
        "id": "16",
        "name": "怪獸之子 Leo",
        "auther": "@ 怪獸之子",
        "price": 5000,
        "img": "https://raw.githubusercontent.com/andy-28/toy/main/17.png",
        "image1": "https://raw.githubusercontent.com/andy-28/toy/main/p01.png",
        "image2": "https://raw.githubusercontent.com/andy-28/toy/main/p02.png",
        "image3": "https://raw.githubusercontent.com/andy-28/toy/main/p03.png",
        "image4": "https://raw.githubusercontent.com/andy-28/toy/main/p04.png",
        "currency": "ETH"
    }
]